import js from '@eslint/js'
import { defineConfig, globalIgnores } from 'eslint/config'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'

/**
 * Architecture boundaries are enforced here instead of by convention:
 *
 *   model -> serializer -> view (Django)  |  api.ts -> queries.ts -> pages -> components
 *
 * - only src/lib/api-client.ts (and the production server adapter) may touch the network
 * - only `*.server.ts` modules and build/server entry files may read `process`
 * - feature api modules stay React-free transport
 * - feature queries own server state and only call their feature api.ts
 * - pages compose queries + UI; they never call api.ts or the transport client directly
 * - presentational components receive props, never server state
 */
const TRANSPORT_ONLY =
  'Network access belongs in src/lib/api-client.ts; import a feature api module instead.'
const SERVER_ONLY_ENV =
  'Browser code cannot read process: move runtime configuration into a *.server.ts module.'
const API_IS_TRANSPORT =
  'Feature api modules are transport + types only: no React, no hooks, no query client.'
const QUERIES_USE_API =
  'queries.ts must go through its feature api.ts, not the generic transport client.'
const PAGES_USE_QUERIES =
  'Pages consume server state through queries.ts, never by calling api.ts directly.'
const PRESENTATIONAL_ONLY =
  'Presentational components take props only: no query client, no api modules, no feature state.'

const apiModulePatterns = ['@/features/*/api', '**/features/*/api', './api', '../api', '../*/api']

const queryModulePatterns = [
  '@/features/*/queries',
  '**/features/*/queries',
  './queries',
  '../queries',
  '../*/queries',
]

const apiClientPatterns = ['@/lib/api-client', '**/lib/api-client']

const queryLibPatterns = ['@tanstack/react-query', '@tanstack/react-query/*']

const noRawNetwork = [
  {
    selector: "MemberExpression[object.name=/^(window|globalThis|self)$/][property.name='fetch']",
    message: TRANSPORT_ONLY,
  },
  {
    selector: "NewExpression[callee.name='XMLHttpRequest']",
    message: TRANSPORT_ONLY,
  },
]

export default defineConfig([
  // routeTree.gen.ts is generated by the TanStack Start plugin.
  globalIgnores(['dist', 'node_modules', 'src/routeTree.gen.ts']),

  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
      'no-console': ['error', { allow: ['error', 'warn', 'info'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-implicit-coercion': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  // Fast-refresh hygiene for component files. Route files are excluded on purpose: a
  // TanStack file route exports `Route` and defines its component locally, which this rule
  // cannot model.
  {
    files: ['src/components/**/*.tsx', 'src/features/**/*.tsx'],
    plugins: { 'react-refresh': reactRefresh },
    rules: {
      'react-refresh/only-export-components': [
        'error',
        { allowConstantExport: true, allowExportNames: ['buttonVariants'] },
      ],
    },
  },

  // Browser code: no raw network, no runtime env.
  {
    files: ['**/*.{ts,tsx}'],
    ignores: ['src/lib/api-client.ts', 'src/**/*.server.ts', 'server.ts', 'vite.config.ts'],
    rules: {
      'no-restricted-globals': [
        'error',
        { name: 'fetch', message: TRANSPORT_ONLY },
        { name: 'XMLHttpRequest', message: TRANSPORT_ONLY },
        { name: 'process', message: SERVER_ONLY_ENV },
      ],
      'no-restricted-syntax': ['error', ...noRawNetwork],
    },
  },

  // The transport client owns fetch, but it is still browser code.
  {
    files: ['src/lib/api-client.ts'],
    rules: {
      'no-restricted-globals': ['error', { name: 'process', message: SERVER_ONLY_ENV }],
    },
  },

  // Feature api modules: transport + types, no React and no query layer.
  {
    files: ['src/features/*/api.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: ['react', 'react-dom', 'react/*', 'react-dom/*'], message: API_IS_TRANSPORT },
            { group: queryLibPatterns, message: API_IS_TRANSPORT },
            { group: ['@tanstack/react-router'], message: API_IS_TRANSPORT },
            { group: queryModulePatterns, message: API_IS_TRANSPORT },
            { group: ['@/components/*', '**/components/*'], message: API_IS_TRANSPORT },
          ],
        },
      ],
    },
  },

  // Feature queries: server state only, always through the feature api module.
  {
    files: ['src/features/*/queries.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: apiClientPatterns, message: QUERIES_USE_API },
            { group: ['@/components/*', '**/components/*'], message: QUERIES_USE_API },
          ],
        },
      ],
    },
  },

  // Pages: compose hooks + UI.
  {
    files: ['src/features/*/pages/**/*.tsx'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: apiModulePatterns, message: PAGES_USE_QUERIES },
            { group: apiClientPatterns, message: PAGES_USE_QUERIES },
          ],
        },
      ],
    },
  },

  // Presentational components: props in, markup out.
  {
    files: ['src/components/**/*.tsx', 'src/features/*/components/**/*.tsx'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: queryLibPatterns, message: PRESENTATIONAL_ONLY },
            { group: apiClientPatterns, message: PRESENTATIONAL_ONLY },
            { group: apiModulePatterns, message: PRESENTATIONAL_ONLY },
            { group: queryModulePatterns, message: PRESENTATIONAL_ONLY },
          ],
        },
      ],
    },
  },
])
