# Railway Deployment Configuration
# This configures the web service only
# Add PostgreSQL via Railway dashboard: Add New > Database > PostgreSQL
# For more info: https://docs.railway.app/reference/config-as-code

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.django"

[build.buildArgs]
NODE_ENV = "production"
VITE_USE_BACKEND_THEMES = "false"
VITE_FRONTEND_THEME = "vercel"

[deploy]
# startCommand removed - using Dockerfile CMD instead
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

# CRITICAL: Volume for persistent media file uploads
# Railway volumes are mounted with root ownership (UID 0)
# MUST set RAILWAY_RUN_UID=0 in environment variables for write permissions
[[deploy.volumes]]
mountPath = "/mnt/media"
