# Generated by Django 5.1.3 on 2025-05-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptiondomain",
            name="subscription",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
        migrations.DeleteModel(
            name="SubscriptionDomain",
        ),
    ]
