# Generated by Django 5.1.3 on 2025-05-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionevent",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={},
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="current_period_start",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="interval",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="plan_type",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="price_amount",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="DomainSubscription",
        ),
        migrations.DeleteModel(
            name="SubscriptionEvent",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
