# Generated by Django 5.1.3 on 2025-05-31 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subscriptionplan_subscription_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="currency",
        ),
    ]
