# Generated by Django 5.1.3 on 2025-05-31 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_currency_field"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
